### ISSUE TITLE
Playbook strategy (serial or parallel)

### ISSUE THREAD

**Issue by solracsf** [amarao/ansible-reboot-if-needed-for-upgrade#3]
Is it possible to add an option to `throttle` the execution and perform it on a 'one by one host' (serial) strategy inside the `[group]`?
https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html

Sometimes parallelism is needed, but sometimes it's not (like a galera cluster where all hosts can't be rebooted at the same time).

**Comment by amarao** [comment]
It's a very old code. Ansible nowadays has `reboot` module and whole role collapses to a simple pair of tasks:
```
- stat: /var/run/reboot-required
  register: reboot_required
- reboot:
  when: reboot_required.stat.exists
```
People, who needs this role (antique ansibles) does not have 'throttle' available.
